Uploading latest Tau SF functions
TopEFT/topeft pull request #408
Opened 2024-04-15 19:33 UTC by anpicci

This PR updates the tau SF implementation to the latest version available

2024-04-15 19:38 UTC, bryates commented
@anpicci please fix the [lint errors](https://github.com/TopEFT/topeft/actions/runs/8695007851/job/23845114599?pr=408#step:4:32)

2024-04-15 19:42 UTC, bryates requested changes
Thanks @anpicci. Overall this is a simple change, but since this relies on changes to TopCoffea (https://github.com/TopEFT/topcoffea/pull/26), we should either update the CI to temporarily check out the `TauSF_update`, or wait until that is merged and then rerun the CI here bem

2024-04-15 19:42 UTC, bryates commented on topeft/modules/corrections.py
> +
```suggestion

```

2024-04-16 10:05 UTC, anpicci commented
Ok, what solution do you prefer @bryates ?

2024-04-16 14:06 UTC, bryates commented
> Ok, which solution do you prefer @bryates ?

I'm leaning towards updating the CI to checkout the temporary branch, so we can get it all running and maybe merge now. That does of course mean we'll have to fix it again later. @Andrew42 and @sscruz what do you think?

2024-06-05 10:00 UTC, anpicci commented
I was wondering if there is any update on this @bryates

2024-06-06 17:34 UTC, bryates commented
> I was wondering if there is any update on this @bryates

@anpicci while we're waiting for the TopCoffea PR, can you fix these lint errors?
https://github.com/TopEFT/topeft/actions/runs/8706515199/job/23879255324?pr=408#step:4:32
It looks like just 2 lines with blank spaces at the end.

2024-07-12 14:39 UTC, bryates approved these changes
Now that the TopCoffea PR has been merged, this PR should be ready. I've merged the laste changes from `master`, and the CI is running now. @anpicci did you have any other updates for this PR?

2024-07-15 10:01 UTC, anpicci commented
@bryates no, I don't need to add anything else, thanks!

2024-07-18 16:00 UTC, anpicci commented
hi @bryates , do you think we can merge?

2024-07-18 16:01 UTC, bryates commented
> hi @bryates , do you think we can merge?

I wanted to make sure @andrea21z and @sscruz don't have any comments, but I'm happy with this PR.

2024-07-19 06:44 UTC, anpicci commented
I'm afraid @andrea21z is not working for CMS anymore

2024-07-19 11:50 UTC, bryates commented
> I'm afraid @andrea21z is not working for CMS anymore

I meant @Andrew42 😂

2024-07-19 17:34 UTC, merged